name: Node.js Package

on:
    release:
        types: [created]

jobs:
    publish-gpr:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
                  registry-url: https://npm.pkg.github.com/
                  scope: '@pmet-public/luma-ui'
            - run: npm install yarn --global
            - run: npm ci
            - run: npm publish
            - run: yarn storybook:deploy
              env:
                  NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
